            - name: generate-multi-source-snake-animation
  # You may pin to the exact commit or the version.
  # uses: Zqzqsb/MultiSourceSnake@a264d256eb8d3b3b1053f033eadc6a76b6f080d2
  uses: Zqzqsb/MultiSourceSnake@v1.1
  with:
    # GitHub user name
    GITHUB_USER: 
    # GitHub token used to fetch the contribution calendar. Default to the action token if empty.
    GITHUB_TOKEN: 
    # Gitee user name
    GITEE_USER: 
    # Gitee token used to access Gitee API.
    GITEE_TOKEN: 
    # list of files to generate.
one file per line. Each output can be customized with options as query string.

 supported query string options:

- palette:      A preset of color, one of [github, github-dark, github-light]
- color_snake:  Color of the snake
- color_dots:   Coma separated list of dots color. 
                The first one is 0 contribution, then it goes from the low contribution to the highest.
                Exactly 5 colors are expected.
example:
  outputs: |
    dark.svg?palette=github-dark&color_snake=blue
    light.svg?color_snake=#7845ab
    ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    outputs: 
          
