name: Generate Snake Animation

on:
  workflow_dispatch:  # Run manually
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mugilan0610
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
